// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.64.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// May be one of the following:
/// --TargetItemID (TargetItemIDType),
/// --TargetItemName (TargetItemNameType),
/// --TargetItemXPath (TargetItemXPathType)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("ChangedFieldType")]
public partial class ChangedFieldType : ExtensionBaseType
{
    #region Private fields
    private BaseType _item;
    #endregion
    
    [XmlElement("TargetItemID", typeof(TargetItemIDType), Order=0)]
    [XmlElement("TargetItemName", typeof(TargetItemNameType), Order=0)]
    [XmlElement("TargetItemXPath", typeof(TargetItemXPathType), Order=0)]
        /// <summary>
        /// May be one of the following:
        /// --TargetItemID (TargetItemIDType),
        /// --TargetItemName (TargetItemNameType),
        /// --TargetItemXPath (TargetItemXPathType)
        /// </summary>
        public virtual BaseType Item
    {
        get
        {
            return _item;
        }
        set
        {
            if ((_item == value))
            {
                return;
            }
            if (((_item == null) 
                        || (_item.Equals(value) != true)))
            {
                _item = value;
                OnPropertyChanged("Item", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether Item should be serialized
    /// </summary>
    public virtual bool ShouldSerializeItem()
    {
        return (_item != null);
    }
}
}
#pragma warning restore
