// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.0.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("DataSourceTypeDatabase")]
public partial class DataSourceTypeDatabase : DataStoreType
{
    private SQL_Type _sQL;
    private bool _sQLSpecified;
    [XmlElement(Order=0)]
    [JsonProperty(Order=0, NullValueHandling=NullValueHandling.Ignore)]
    public virtual SQL_Type SQL
    {
        get
        {
            return _sQL;
        }
        set
        {
            if ((_sQL == value))
            {
                return;
            }
            if (((_sQL == null) 
                        || (_sQL.Equals(value) != true)))
            {
                _sQL = value;
                OnPropertyChanged("SQL", value);
            }
        }
    }
    
    [JsonIgnore]
    [XmlIgnore()]
    public bool SQLSpecified
    {
        get
        {
            return _sQLSpecified;
        }
        set
        {
            _sQLSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether SQL should be serialized
    /// </summary>
    public virtual bool ShouldSerializeSQL()
    {
        return (SQL != null);
    }
}
}
#pragma warning restore
