// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.0.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// Represents questions. Parent items may be Section, Question, and
/// ListItem.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("QuestionItemType")]
public partial class QuestionItemType : QuestionItemBaseType
{
    private ChildItemsType _item1;
    private bool _item1Specified;
    [XmlElement("ChildItems", Order=0)]
    [JsonProperty("ChildItems", Order=0, NullValueHandling=NullValueHandling.Ignore)]
    public virtual ChildItemsType Item1
    {
        get
        {
            return _item1;
        }
        set
        {
            if ((_item1 == value))
            {
                return;
            }
            if (((_item1 == null) 
                        || (_item1.Equals(value) != true)))
            {
                _item1 = value;
                OnPropertyChanged("Item1", value);
            }
        }
    }
    
    [JsonIgnore]
    [XmlIgnore()]
    public bool Item1Specified
    {
        get
        {
            return _item1Specified;
        }
        set
        {
            _item1Specified = value;
        }
    }
    
    /// <summary>
    /// Test whether Item1 should be serialized
    /// </summary>
    public virtual bool ShouldSerializeItem1()
    {
        return (Item1 != null);
    }
}
}
#pragma warning restore
