// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.64.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("InterfaceTypeFieldsField")]
public partial class InterfaceTypeFieldsField : ExtensionBaseType
{
    #region Private fields
    private string_Stype _getter;
    private string_Stype _setter;
    private string_Stype _action;
    #endregion
    
    [XmlElement(Order=0)]
    [JsonProperty(Order=0, NullValueHandling=NullValueHandling.Ignore)]
    public virtual string_Stype Getter
    {
        get
        {
            return _getter;
        }
        set
        {
            if ((_getter == value))
            {
                return;
            }
            if (((_getter == null) 
                        || (_getter.Equals(value) != true)))
            {
                _getter = value;
                OnPropertyChanged("Getter", value);
            }
        }
    }
    
    [XmlElement(Order=1)]
    [JsonProperty(Order=1, NullValueHandling=NullValueHandling.Ignore)]
    public virtual string_Stype Setter
    {
        get
        {
            return _setter;
        }
        set
        {
            if ((_setter == value))
            {
                return;
            }
            if (((_setter == null) 
                        || (_setter.Equals(value) != true)))
            {
                _setter = value;
                OnPropertyChanged("Setter", value);
            }
        }
    }
    
    [XmlElement(Order=2)]
    [JsonProperty(Order=2, NullValueHandling=NullValueHandling.Ignore)]
    public virtual string_Stype Action
    {
        get
        {
            return _action;
        }
        set
        {
            if ((_action == value))
            {
                return;
            }
            if (((_action == null) 
                        || (_action.Equals(value) != true)))
            {
                _action = value;
                OnPropertyChanged("Action", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether Getter should be serialized
    /// </summary>
    public virtual bool ShouldSerializeGetter()
    {
        return (_getter != null);
    }
    
    /// <summary>
    /// Test whether Setter should be serialized
    /// </summary>
    public virtual bool ShouldSerializeSetter()
    {
        return (_setter != null);
    }
    
    /// <summary>
    /// Test whether Action should be serialized
    /// </summary>
    public virtual bool ShouldSerializeAction()
    {
        return (_action != null);
    }
}
}
#pragma warning restore
