// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.0.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("HashType")]
public partial class HashType : base64Binary_Stype
{
    #region Private fields
    private string _hashAlgorithm;
    private bool _hashAlgorithmSpecified;
    #endregion
    
    [XmlAttribute]
    [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual string hashAlgorithm
    {
        get
        {
            return _hashAlgorithm;
        }
        set
        {
            if ((_hashAlgorithm == value))
            {
                return;
            }
            if (((_hashAlgorithm == null) 
                        || (_hashAlgorithm.Equals(value) != true)))
            {
                _hashAlgorithm = value;
                OnPropertyChanged("hashAlgorithm", value);
            }
        }
    }
    
    [JsonIgnore]
    [XmlIgnore()]
    public bool hashAlgorithmSpecified
    {
        get
        {
            return _hashAlgorithmSpecified;
        }
        set
        {
            _hashAlgorithmSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether hashAlgorithm should be serialized
    /// </summary>
    public virtual bool ShouldSerializehashAlgorithm()
    {
        return !string.IsNullOrEmpty(hashAlgorithm);
    }
}
}
#pragma warning restore
