// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.0.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// Function or web service that returns a string
/// value.
/// </summary>
[XmlInclude(typeof(LookupEndPointType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("CallFuncActionType")]
public partial class CallFuncActionType : CallFuncType
{
    private PredActionType _conditionalActions;
    private bool _conditionalActionsSpecified;
    /// <summary>
    /// Actions to take, usually based on the return @val
    /// value of the function. Condiitons may be specified for each action.
    /// Conditions may be combined by Boolean operators and nested to any
    /// level.
    /// </summary>
    [XmlElement(Order=0)]
    [JsonProperty(Order=0, NullValueHandling=NullValueHandling.Ignore)]
    public virtual PredActionType ConditionalActions
    {
        get
        {
            return _conditionalActions;
        }
        set
        {
            if ((_conditionalActions == value))
            {
                return;
            }
            if (((_conditionalActions == null) 
                        || (_conditionalActions.Equals(value) != true)))
            {
                _conditionalActions = value;
                OnPropertyChanged("ConditionalActions", value);
            }
        }
    }
    
    [JsonIgnore]
    [XmlIgnore()]
    public bool ConditionalActionsSpecified
    {
        get
        {
            return _conditionalActionsSpecified;
        }
        set
        {
            _conditionalActionsSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether ConditionalActions should be serialized
    /// </summary>
    public virtual bool ShouldSerializeConditionalActions()
    {
        return (ConditionalActions != null);
    }
}
}
#pragma warning restore
