// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

/// <summary>
/// Function or web service that returns a string value.
/// </summary>
[XmlInclude(typeof(LookupEndPointType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class CallFuncType : CallFuncBaseType
{
    #region Private fields
    private string _dataType;
    private bool _dataTypeSpecified;
    #endregion
    
    /// <summary>
    /// CallFuncType class constructor
    /// </summary>
    public CallFuncType()
    {
        _dataType = "string";
    }
    
    [XmlAttribute]
    [DefaultValue("string")]
    public virtual string dataType
    {
        get
        {
            return _dataType;
        }
        set
        {
            if ((_dataType == value))
            {
                return;
            }
            if (((_dataType == null) 
                        || (_dataType.Equals(value) != true)))
            {
                _dataType = value;
                OnPropertyChanged("dataType", value);
            }
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool dataTypeSpecified
    {
        get
        {
            return _dataTypeSpecified;
        }
        set
        {
            _dataTypeSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether dataType should be serialized
    /// </summary>
    public virtual bool ShouldSerializedataType()
    {
        return !string.IsNullOrEmpty(dataType);
    }
}
}
#pragma warning restore
