// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

/// <summary>
/// This type provides information about an Applications Programming Interface (API)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class InterfaceType : ExtensionBaseType
{
    #region Private fields
    private string_Stype _identifer;
    private string_Stype _interfaceName;
    private string_Stype _description;
    private string_Stype _uRL;
    private string_Stype _version;
    private InterfaceTypeFields _fields;
    private InterfaceTypeDocumentation _documentation;
    private bool _identiferSpecified;
    private bool _interfaceNameSpecified;
    private bool _descriptionSpecified;
    private bool _uRLSpecified;
    private bool _versionSpecified;
    private bool _fieldsSpecified;
    private bool _documentationSpecified;
    #endregion
    
    [XmlElement(Order=0)]
    public virtual string_Stype Identifer
    {
        get
        {
            return _identifer;
        }
        set
        {
            if ((_identifer == value))
            {
                return;
            }
            if (((_identifer == null) 
                        || (_identifer.Equals(value) != true)))
            {
                _identifer = value;
                OnPropertyChanged("Identifer", value);
            }
        }
    }
    
    [XmlElement(Order=1)]
    public virtual string_Stype InterfaceName
    {
        get
        {
            return _interfaceName;
        }
        set
        {
            if ((_interfaceName == value))
            {
                return;
            }
            if (((_interfaceName == null) 
                        || (_interfaceName.Equals(value) != true)))
            {
                _interfaceName = value;
                OnPropertyChanged("InterfaceName", value);
            }
        }
    }
    
    [XmlElement(Order=2)]
    public virtual string_Stype Description
    {
        get
        {
            return _description;
        }
        set
        {
            if ((_description == value))
            {
                return;
            }
            if (((_description == null) 
                        || (_description.Equals(value) != true)))
            {
                _description = value;
                OnPropertyChanged("Description", value);
            }
        }
    }
    
    [XmlElement(Order=3)]
    public virtual string_Stype URL
    {
        get
        {
            return _uRL;
        }
        set
        {
            if ((_uRL == value))
            {
                return;
            }
            if (((_uRL == null) 
                        || (_uRL.Equals(value) != true)))
            {
                _uRL = value;
                OnPropertyChanged("URL", value);
            }
        }
    }
    
    [XmlElement(Order=4)]
    public virtual string_Stype Version
    {
        get
        {
            return _version;
        }
        set
        {
            if ((_version == value))
            {
                return;
            }
            if (((_version == null) 
                        || (_version.Equals(value) != true)))
            {
                _version = value;
                OnPropertyChanged("Version", value);
            }
        }
    }
    
    [XmlElement(Order=5)]
    public virtual InterfaceTypeFields Fields
    {
        get
        {
            return _fields;
        }
        set
        {
            if ((_fields == value))
            {
                return;
            }
            if (((_fields == null) 
                        || (_fields.Equals(value) != true)))
            {
                _fields = value;
                OnPropertyChanged("Fields", value);
            }
        }
    }
    
    [XmlElement(Order=6)]
    public virtual InterfaceTypeDocumentation Documentation
    {
        get
        {
            return _documentation;
        }
        set
        {
            if ((_documentation == value))
            {
                return;
            }
            if (((_documentation == null) 
                        || (_documentation.Equals(value) != true)))
            {
                _documentation = value;
                OnPropertyChanged("Documentation", value);
            }
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool IdentiferSpecified
    {
        get
        {
            return _identiferSpecified;
        }
        set
        {
            _identiferSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool InterfaceNameSpecified
    {
        get
        {
            return _interfaceNameSpecified;
        }
        set
        {
            _interfaceNameSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool DescriptionSpecified
    {
        get
        {
            return _descriptionSpecified;
        }
        set
        {
            _descriptionSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool URLSpecified
    {
        get
        {
            return _uRLSpecified;
        }
        set
        {
            _uRLSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool VersionSpecified
    {
        get
        {
            return _versionSpecified;
        }
        set
        {
            _versionSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool FieldsSpecified
    {
        get
        {
            return _fieldsSpecified;
        }
        set
        {
            _fieldsSpecified = value;
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool DocumentationSpecified
    {
        get
        {
            return _documentationSpecified;
        }
        set
        {
            _documentationSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether Identifer should be serialized
    /// </summary>
    public virtual bool ShouldSerializeIdentifer()
    {
        return (_identifer != null);
    }
    
    /// <summary>
    /// Test whether InterfaceName should be serialized
    /// </summary>
    public virtual bool ShouldSerializeInterfaceName()
    {
        return (_interfaceName != null);
    }
    
    /// <summary>
    /// Test whether Description should be serialized
    /// </summary>
    public virtual bool ShouldSerializeDescription()
    {
        return (_description != null);
    }
    
    /// <summary>
    /// Test whether URL should be serialized
    /// </summary>
    public virtual bool ShouldSerializeURL()
    {
        return (_uRL != null);
    }
    
    /// <summary>
    /// Test whether Version should be serialized
    /// </summary>
    public virtual bool ShouldSerializeVersion()
    {
        return (_version != null);
    }
    
    /// <summary>
    /// Test whether Fields should be serialized
    /// </summary>
    public virtual bool ShouldSerializeFields()
    {
        return (_fields != null);
    }
    
    /// <summary>
    /// Test whether Documentation should be serialized
    /// </summary>
    public virtual bool ShouldSerializeDocumentation()
    {
        return (_documentation != null);
    }
}
}
#pragma warning restore
