// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

/// <summary>
/// Can hold one or more of the following:
/// --Action (ActActionType)
/// --AddCode (ActAddCodeType)
/// --CallFunction (CallFuncActionType)
/// --ConditionalGroupAction (PredActionType)
/// --Inject (ActInjectType)
/// --PreviewReport (ActPreviewReportType)
/// --RunCode (ScriptCodeAnyType)
/// --Save (ActSaveResponsesType)
/// --SelectMatchingListItems (RuleSelectMatchingListItemsType)
/// --SendMessage111 (ActSendMessageType)
/// --SendReport (ActSendReportType)
/// --SetAttributeValue (ActSetAttributeType)
/// --SetAttributeValueScript (ActSetAttrValueScriptType)
/// --SetBoolAttributeValueCode (ActSetBoolAttributeValueCodeType)
/// --ShowForm (ActShowFormType)
/// --ShowMessage (ActShowMessageType)
/// --ShowReport (ActShowReportType)
/// --ShowURL (CallFuncActionType)
/// --ValidateForm (ActValidateFormType)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016", IncludeInSchema=false)]
public enum ItemsChoiceType
{
    Action,
    AddCode,
    CallFunction,
    ConditionalGroupAction,
    Inject,
    PreviewReport,
    RunCode,
    Save,
    SelectMatchingListItems,
    SendMessage111,
    SendReport,
    SetAttributeValue,
    SetAttributeValueScript,
    SetBoolAttributeValueCode,
    ShowForm,
    ShowMessage,
    ShowReport,
    ShowURL,
    ValidateForm,
}
}
#pragma warning restore
