// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// SDC datatypes for Data Entry (DE), based mostly on W3C specifications. Uses base Attributes and Extension capability to enhance the list of Data Types. Includes additonal metadata to specify data input restrictions for data entry forms, and to aid in validation of SDC form responses in SDC XML instance documents.
/// Must be one of the following:
/// --HTML (HTML_DEtype)
/// --XML (XML_DEtype)
/// --anyType (anyType_DEtype)
/// --anyURI (anyURI_DEtype)
/// --base64Binary (base64Binary_DEtype)
/// --boolean (boolean_DEtype)
/// --byte (byte_DEtype)
/// --date (date_DEtype)
/// --dateTime (dateTime_DEtype)
/// --dateTimeStamp (dateTimeStamp_DEtype)
/// --decimal (decimal_DEtype)
/// --double (double_DEtype)
/// --duration (duration_DEtype)
/// --float (float_DEtype)
/// --gDay (gDay_DEtype)
/// --gMonth (gMonth_DEtype)
/// --gMonthDay (gMonthDay_DEtype)
/// --gYear (gYear_DEtype)
/// --gYearMonth (gMonth_DEtype)
/// --hexBinary (hexBinary_DEtype)
/// --int (int_DEtype)
/// --integer (integer_DEtype)
/// --long (long_DEtype)
/// --negativeInteger (negativeInteger_DEtype)
/// --nonNegativeInteger (nonNegativeInteger_DEtype)
/// --nonPositiveInteger (nonPositiveInteger_DEtype)
/// --positiveInteger (positiveInteger_DEtype)
/// --short (short_DEtype)
/// --string (string_DEtype)
/// --time (time_DEtype)
/// --unsignedByte (unsignedByte_DEtype)
/// --unsignedInt (unsignedInt_DEtype)
/// --unsignedLong (unsignedLong_DEtype)
/// --unsignedShort (unsignedShort_DEtype)
/// --yearMonthDuration (yearMonthDuration_DEtype)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016", IncludeInSchema=false)]
public enum ItemChoiceType1
{
    HTML,
    XML,
    anyType,
    anyURI,
    base64Binary,
    boolean,
    @byte,
    date,
    dateTime,
    dateTimeStamp,
    dayTimeDuration,
    @decimal,
    @double,
    duration,
    @float,
    gDay,
    gMonth,
    gMonthDay,
    gYear,
    gYearMonth,
    hexBinary,
    @int,
    integer,
    @long,
    negativeInteger,
    nonNegativeInteger,
    nonPositiveInteger,
    positiveInteger,
    @short,
    @string,
    time,
    unsignedByte,
    unsignedInt,
    unsignedLong,
    unsignedShort,
    yearMonthDuration,
}
}
#pragma warning restore
