// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// The type is a standard way to point to a named item anywhere in a FormDesign template.  A named item is any element that has the @name attribute set to a unique value.
/// </summary>
[XmlInclude(typeof(ActAddCodeType))]
[XmlInclude(typeof(ItemNameAttributeType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("ItemNameType")]
public partial class ItemNameType : ExtensionBaseType
{
    #region Private fields
    private string _itemName;
    private bool _itemNameSpecified;
    #endregion
    
    /// <summary>
    /// The @name attribute of the referenced element.
    /// </summary>
    [XmlAttribute(DataType="NCName")]
    [Required]
    [JsonProperty(NullValueHandling=NullValueHandling.Ignore)]
    public virtual string itemName
    {
        get
        {
            return _itemName;
        }
        set
        {
            if ((_itemName == value))
            {
                return;
            }
            if (((_itemName == null) 
                        || (_itemName.Equals(value) != true)))
            {
                ValidationContext validatorPropContext = new ValidationContext(this, null, null);
                validatorPropContext.MemberName = "itemName";
                Validator.ValidateProperty(value, validatorPropContext);
                _itemName = value;
                OnPropertyChanged("itemName", value);
            }
        }
    }
    
    [JsonIgnore]
    [XmlIgnore()]
    public bool itemNameSpecified
    {
        get
        {
            return _itemNameSpecified;
        }
        set
        {
            _itemNameSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether itemName should be serialized
    /// </summary>
    public virtual bool ShouldSerializeitemName()
    {
        return !string.IsNullOrEmpty(itemName);
    }
}
}
#pragma warning restore
