// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

/// <summary>
/// SDC datatypes in Simple (SType) format, based mostly on W3C specifications.  Uses base Attributes and Extension capability to enhance the list of Data Types.
/// Must be one of the following:
/// --dateTime (dateTime_Stype)
/// --dateTimeStamp (dateTimeStamp_Stype)
/// --duration (duration_Stype)
/// --dayTimeDuration (dayTimeDuration_Stype)
/// --gDay (gDay_Stype)
/// --gMonth (gMonth_Stype)
/// --gMonthDay (gMonthDay_Stype)
/// --gYear (gYear_Stype)
/// --gYearMonth (gMonth_Stype)
/// --time (time_Stype)
/// --yearMonthDuration (yearMonthDuration_Stype)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016", IncludeInSchema=false)]
public enum ItemChoiceType3
{
    date,
    dateTime,
    dateTimeStamp,
    dayTimeDuration,
    duration,
    gDay,
    gMonth,
    gMonthDay,
    gYear,
    gYearMonth,
    time,
    yearMonthDuration,
}
}
#pragma warning restore
