// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
public partial class ProvenanceType : ExtensionBaseType
{
    #region Private fields
    private List<FileType> _replacedFile;
    private bool _replacedFileSpecified;
    #endregion
    
    [XmlElement("ReplacedFile", Order=0)]
    public virtual List<FileType> ReplacedFile
    {
        get
        {
            return _replacedFile;
        }
        set
        {
            if ((_replacedFile == value))
            {
                return;
            }
            if (((_replacedFile == null) 
                        || (_replacedFile.Equals(value) != true)))
            {
                _replacedFile = value;
                OnPropertyChanged("ReplacedFile", value);
            }
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool ReplacedFileSpecified
    {
        get
        {
            return _replacedFileSpecified;
        }
        set
        {
            _replacedFileSpecified = value;
        }
    }
    
    /// <summary>
    /// Test whether ReplacedFile should be serialized
    /// </summary>
    public virtual bool ShouldSerializeReplacedFile()
    {
        return ReplacedFile != null && ReplacedFile.Count > 0;
    }
}
}
#pragma warning restore
