// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 7.0.197.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Text.Json;
using System.Text.Json.Serialization;
using MessagePack;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using  System.Text.Json;

/// <summary>
/// This certificate is a structured document in ASN.1 format, that is created by a certificate authority (CA) to verify that certifiacte owner (the signer) has registered his/her/its identity with the CA.  The certificate contains information about the signer and the CA, and also contains the public key of the signer.  The signer's public key (obtained from the certificate) may be used to verify or decrypt any document signed by the signer.
/// 
/// The signer's certificate is signed with the CA's public key, and thus the CA's public key may be used to verify the validity of the signer's certificate.  The CA's public key can be stored locally or may be obtained directly from the CA's own certificate.  A long list of CA certificates is provided with the operating system software of most systems.
/// 
/// Software to verify signatures and certificates and decrypt documents is provided with most operating systems and most programming languages.
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="urn:ihe:qrph:sdc:2016")]
public partial class TemplateAdminTypeDigitalSignatureSignaturePropertiesSignerPublicKeyCertificate : BaseType
{
    #region Private fields
    private byte[] _val;
    private bool _valSpecified;
    #endregion
    
    [XmlAttribute(DataType="base64Binary")]
    public virtual byte[] val
    {
        get
        {
            return _val;
        }
        set
        {
            if ((_val == value))
            {
                return;
            }
            if (((_val == null) 
                        || (_val.Equals(value) != true)))
            {
                _val = value;
                OnPropertyChanged("val", value);
            }
        }
    }
    
    [System.Text.Json.JsonIgnoreAttribute()]
    [XmlIgnore()]
    public bool valSpecified
    {
        get
        {
            return _valSpecified;
        }
        set
        {
            _valSpecified = value;
        }
    }
}
}
#pragma warning restore
