// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 6.0.64.0. www.xsd2code.com
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using MsgPack.Serialization;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// A structure to describe a type of employment
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("JobType")]
public partial class JobType : ExtensionBaseType
{
    #region Private fields
    private List<string_Stype> _jobTitle;
    private OrganizationType _organization;
    private date_Stype _startDate;
    private date_Stype _stopDate;
    private string_Stype _description;
    #endregion
    
    [XmlElement("JobTitle", Order=0)]
    [JsonProperty(Order=0, NullValueHandling=NullValueHandling.Ignore)]
    public virtual List<string_Stype> JobTitle
    {
        get
        {
            return _jobTitle;
        }
        set
        {
            if ((_jobTitle == value))
            {
                return;
            }
            if (((_jobTitle == null) 
                        || (_jobTitle.Equals(value) != true)))
            {
                _jobTitle = value;
                OnPropertyChanged("JobTitle", value);
            }
        }
    }
    
    [XmlElement(Order=1)]
    [JsonProperty(Order=1, NullValueHandling=NullValueHandling.Ignore)]
    public virtual OrganizationType Organization
    {
        get
        {
            return _organization;
        }
        set
        {
            if ((_organization == value))
            {
                return;
            }
            if (((_organization == null) 
                        || (_organization.Equals(value) != true)))
            {
                _organization = value;
                OnPropertyChanged("Organization", value);
            }
        }
    }
    
    [XmlElement(Order=2)]
    [JsonProperty(Order=2, NullValueHandling=NullValueHandling.Ignore)]
    public virtual date_Stype StartDate
    {
        get
        {
            return _startDate;
        }
        set
        {
            if ((_startDate == value))
            {
                return;
            }
            if (((_startDate == null) 
                        || (_startDate.Equals(value) != true)))
            {
                _startDate = value;
                OnPropertyChanged("StartDate", value);
            }
        }
    }
    
    [XmlElement(Order=3)]
    [JsonProperty(Order=3, NullValueHandling=NullValueHandling.Ignore)]
    public virtual date_Stype StopDate
    {
        get
        {
            return _stopDate;
        }
        set
        {
            if ((_stopDate == value))
            {
                return;
            }
            if (((_stopDate == null) 
                        || (_stopDate.Equals(value) != true)))
            {
                _stopDate = value;
                OnPropertyChanged("StopDate", value);
            }
        }
    }
    
    /// <summary>
    /// Job Description
    /// </summary>
    [XmlElement(Order=4)]
    [JsonProperty(Order=4, NullValueHandling=NullValueHandling.Ignore)]
    public virtual string_Stype Description
    {
        get
        {
            return _description;
        }
        set
        {
            if ((_description == value))
            {
                return;
            }
            if (((_description == null) 
                        || (_description.Equals(value) != true)))
            {
                _description = value;
                OnPropertyChanged("Description", value);
            }
        }
    }
    
    /// <summary>
    /// Test whether JobTitle should be serialized
    /// </summary>
    public virtual bool ShouldSerializeJobTitle()
    {
        return JobTitle != null && JobTitle.Count > 0;
    }
    
    /// <summary>
    /// Test whether Organization should be serialized
    /// </summary>
    public virtual bool ShouldSerializeOrganization()
    {
        return (_organization != null);
    }
    
    /// <summary>
    /// Test whether StartDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeStartDate()
    {
        return (_startDate != null);
    }
    
    /// <summary>
    /// Test whether StopDate should be serialized
    /// </summary>
    public virtual bool ShouldSerializeStopDate()
    {
        return (_stopDate != null);
    }
    
    /// <summary>
    /// Test whether Description should be serialized
    /// </summary>
    public virtual bool ShouldSerializeDescription()
    {
        return (_description != null);
    }
}
}
#pragma warning restore
