// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.1.0. www.xsd2code.com
//  </auto-generated>
//  Extensively modified rlm 2020_05_11
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Bson;
    //using J = System.Text.Bson;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;

    public static partial class SdcSerializerBson<T> where T : ITopNode

    {
        // Two separate JsonSerializer instances are required:
        //
        // _serializerBsonWrite  — used for SERIALIZATION (reading object properties to produce BSON).
        //   No ContractResolver: xsd2code++ backing fields are null until the property getter is
        //   called (lazy init), so property getters must be used to read the real values.
        //
        // _serializerBsonRead   — used for DESERIALIZATION (writing values back into objects).
        //   No ContractResolver: property setters are called normally; validation and tree-mutation
        //   side-effects are suppressed by SdcUtil.IsDeserializing.Value = true for the duration
        //   of the call, then ReflectRefreshTree rebuilds the node registries afterward.

        private static JsonSerializer _serializerBsonWrite;
        private static JsonSerializer SerializerBsonWrite
        {
            get
            {
                if (_serializerBsonWrite == null)
                {
                    // TypeNameHandling.All: emit "$type" discriminators for all polymorphic collection elements.
                    // Security note: safe for internal/trusted round-trips; use a SerializationBinder for untrusted input.
                    _serializerBsonWrite = new JsonSerializer
                    {
                        TypeNameHandling    = TypeNameHandling.All,
                        ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                        // FloatFormatHandling.String: write NaN/Infinity as strings rather than crashing.
                        FloatFormatHandling  = FloatFormatHandling.String,
                        // DateTimeZoneHandling.Utc: normalise DateTime.Kind to UTC for round-trip fidelity.
                        DateTimeZoneHandling = DateTimeZoneHandling.Utc
                        // No ContractResolver: let Json.NET call property getters normally so that
                        // lazy-initialized xsd2code++ properties return their real values.
                    };
                    // Normalise decimal scale so that whole-number decimals (e.g. 2M) are written
                    // without a trailing fractional zero, matching the XML attribute representation.
                    _serializerBsonWrite.Converters.Add(SdcJsonDecimalConverter.Instance);
                }
                return _serializerBsonWrite;
            }
        }

        private static JsonSerializer _serializerBsonRead;
        private static JsonSerializer SerializerBsonRead
        {
            get
            {
                if (_serializerBsonRead == null)
                {
                    // TypeNameHandling.All: read "$type" discriminators written during serialization.
                    // ConstructorHandling: use protected/internal parameterless constructors so Newtonsoft
                    // does not invoke the public parent-dependent constructors with a null parentNode.
                    // No ContractResolver: property setters are called normally; their validation and
                    // tree-mutation side-effects are suppressed by IsDeserializing.Value = true.
                    _serializerBsonRead = new JsonSerializer
                    {
                        TypeNameHandling    = TypeNameHandling.All,
                        ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                        // FloatFormatHandling.String: read back NaN/Infinity written as strings.
                        FloatFormatHandling  = FloatFormatHandling.String,
                        // DateTimeZoneHandling.Utc: normalise DateTime.Kind to UTC for round-trip fidelity.
                        DateTimeZoneHandling = DateTimeZoneHandling.Utc
                    };
                    // Normalise decimal scale on read-back so "2.0" is stored as 2M (scale 0),
                    // matching the value originally loaded from XML.
                    _serializerBsonRead.Converters.Add(SdcJsonDecimalConverter.Instance);
                }
                return _serializerBsonRead;
            }
        }
        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current SdcEntityBase object into an XML string
        /// </summary>
        /// <returns>string XML value</returns>
        public static string SerializeBson<T>(T obj)
        {
            MemoryStream memoryStream = null;
            try
            {
                memoryStream = new MemoryStream();
                BsonDataWriter bsonDataWriter = new BsonDataWriter(memoryStream);
                // Use write serializer (no contract resolver) so lazy-init getters are called normally.
                SerializerBsonWrite.Serialize(bsonDataWriter, obj);
                return Convert.ToBase64String(memoryStream.ToArray());
            }
            finally
            {
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes SdcEntityBase object
        /// </summary>
        /// <param name="input">string to deserialize</param>
        /// <param name="obj">Output SdcEntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
        public static bool DeserializeBson(string input, out T obj, out Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = DeserializeBson(input);
                return true;
            }
            catch (Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool DeserializeBson(string input, out T obj)
        {
            Exception exception = null;
            return DeserializeBson(input, out obj, out exception);
        }

        /// <returns>string XML value</returns>
        public static T DeserializeBson(string input)
        {
            MemoryStream memoryStream = null;
            try
            {
                byte[] data;
                data = Convert.FromBase64String(input);
                memoryStream = new MemoryStream(data);
                BsonDataReader bsonDataReader = new BsonDataReader(memoryStream);
                // DateTimeKindHandling.Utc: the BSON Date type stores an absolute UTC instant, but
                // BsonDataReader defaults to DateTimeKind.Local and re-projects that instant into the
                // host's local zone on read, shifting the tick count by the local UTC offset (so an
                // xs:date/xs:dateTime/xs:dateTimeStamp value round-tripped through BSON came back
                // off by the host offset). Reading as Utc returns the stored instant unchanged,
                // giving exact tick parity with the XML/JSON/MsgPack round-trips.
                bsonDataReader.DateTimeKindHandling = DateTimeKind.Utc;
                try
                {
                    // Set IsDeserializing to suppress setter side-effects (validation, tree-mutation)
                    // during reconstruction; ReflectRefreshTree rebuilds the node registries after.
                    SdcUtil.IsDeserializing.Value = true;
                    SdcUtil.SuppressValidation.Value = true;
                    var result = SerializerBsonRead.Deserialize<T>(bsonDataReader);
                    if (result is BaseType bt)
                    {
                        try { SdcUtil.ReflectRefreshTree(bt.TopNode ?? (ITopNode)bt, out _, print: false, refreshTree: true); } catch { }
                    }
                    SdcUtil.IsDeserializing.Value = false;
                    SdcUtil.SuppressValidation.Value = false;
                    return result;
                }
                finally
                {
                    SdcUtil.IsDeserializing.Value = false;
                    SdcUtil.SuppressValidation.Value = false;
                }
            }
            finally
            {
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }
        #endregion

        /// <summary>
        /// Deserializes BSON and validates all node properties as values are assigned to setters.
        /// Unlike <see cref="DeserializeBson(string)"/>, this overload sets
        /// <see cref="SdcUtil.SuppressValidation"/> to <see langword="false"/> so that every
        /// property setter runs DataAnnotations validation during deserialization.
        /// </summary>
        /// <returns>
        /// A tuple of the deserialized object and an <see cref="SdcValidationReport"/> containing
        /// any validation issues found.
        /// </returns>
        public static (T result, SdcValidationReport report) DeserializeBsonValidating(string input)
        {
            var report = new SdcValidationReport();
            MemoryStream memoryStream = null;
            try
            {
                byte[] data = Convert.FromBase64String(input);
                memoryStream = new MemoryStream(data);
                BsonDataReader bsonDataReader = new BsonDataReader(memoryStream);
                // DateTimeKindHandling.Utc: see DeserializeBson — read the stored UTC instant as Utc
                // instead of re-projecting it into the host local zone (which shifts the tick count).
                bsonDataReader.DateTimeKindHandling = DateTimeKind.Utc;
                SdcUtil.IsDeserializing.Value     = true;
                SdcUtil.SuppressValidation.Value  = false;  // enable setter validation during load
                SdcUtil.ValidationCollector.Value = report;
                T result;
                try
                {
                    result = SerializerBsonRead.Deserialize<T>(bsonDataReader);
                }
                finally
                {
                    SdcUtil.IsDeserializing.Value     = false;
                    SdcUtil.SuppressValidation.Value  = false;
                    SdcUtil.ValidationCollector.Value = null;
                }
                if (result is BaseType bt)
                {
                    try { SdcUtil.ReflectRefreshTree(bt.TopNode ?? (ITopNode)bt, out _, print: false, refreshTree: true); } catch { }
                }
                return (result, report);
            }
            finally
            {
                memoryStream?.Dispose();
            }
        }

        public static void SaveToFileBson<T>(string fileName, T obj)
        {
            StreamWriter streamWriter = null;
            try
            {
                string dataString = SerializeBson(obj);
                FileInfo outputFile = new FileInfo(fileName);
                streamWriter = outputFile.CreateText();
                streamWriter.WriteLine(dataString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        public static T LoadFromFileBson(string fileName)
        {
            FileStream file = null;
            StreamReader sr = null;
            try
            {
                file = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new StreamReader(file);
                string dataString = sr.ReadToEnd();
                sr.Close();
                file.Close();

				BaseType.ResetLastTopNode();
				T obj = DeserializeBson(dataString);
				BaseType.ResetLastTopNode();
				return obj;
			}
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
    }
}

#pragma warning restore