// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 5.1.1.0. www.xsd2code.com
//  </auto-generated>
//  Extensively modified rlm 2020_05_11
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using Newtonsoft.Json;
	using J = System.Text.Json;
	using System.IO;
	using System.Text;
	using System.Xml;
	using System.Collections.Generic;
	using System.Runtime.CompilerServices;

	public static partial class SdcSerializerJson<T> where T : ITopNode

	{

		#region Serialize/Deserialize
		/// <summary>
		/// Serializes current EntityBase object into an json string
		/// </summary>
		public static string SerializeJson<T>(T obj)
		{
			// TypeNameHandling.All writes "$type" discriminators for every polymorphic collection element
			// (e.g. ChildItemsList: List<IdentifiedExtensionType> containing SectionItemType, QuestionItemType, etc.).
			// Without this, deserialization cannot reconstruct the correct concrete types.
			// Security note: TypeNameHandling.All is safe for internal/trusted round-trips. When accepting
			// JSON from untrusted sources, supply a custom SerializationBinder that whitelists only SDC.Schema types.
			return JsonConvert.SerializeObject(obj, new JsonSerializerSettings
			{
				TypeNameHandling = TypeNameHandling.All
			});
		}

		/// <summary>
		/// Deserializes workflow markup into an EntityBase object
		/// </summary>
		/// <param name="input">string workflow markup to deserialize</param>
		/// <param name="obj">Output EntityBase object</param>
		/// <param name="exception">output Exception value if deserialize failed</param>
		/// <returns>true if this Serializer can deserialize the object; otherwise, false</returns>
		public static bool DeserializeJson<T>(string input, out T obj, out System.Exception exception)
		{
			exception = null;
			obj = default(T);
			try
			{
				obj = DeserializeJson<T>(input);
				//obj = J.JsonSerializer.Deserialize<T>(input);  //System.Text.Json
				return true;
			}
			catch (System.Exception ex)
			{
				exception = ex;
				return false;
			}
		}

		public static bool DeserializeJson<T>(string input, out T obj)
		{
			System.Exception exception = null;
			return DeserializeJson<T>(input, out obj, out exception);
		}

		public static T DeserializeJson<T>(string input)
		{
			// ConstructorHandling: use protected/internal parameterless constructors so Json.NET does not
			// invoke the public parent-dependent constructors with a null parentNode argument.
			// TypeNameHandling.All: read the "$type" discriminators written by SerializeJson so that
			// polymorphic collection elements (e.g. ChildItemsList) are deserialized as the correct
			// concrete types (SectionItemType, QuestionItemType, etc.) rather than as the abstract base type.
			var settings = new JsonSerializerSettings
			{
				TypeNameHandling    = TypeNameHandling.All,
				ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor
			};

			// Use a contract resolver that writes directly to generated backing fields
			// to avoid invoking property setters (which perform runtime validation)
			// during deserialization. This preserves the original behavior where
			// validation runs only during normal runtime assignments, not during
			// low-level model reconstruction.
			settings.ContractResolver = new SdcNoSetterContractResolver();
			try
			{
				return JsonConvert.DeserializeObject<T>(input, settings);
			}
			catch (System.Exception ex)
			{
				// Dump input to temp file to aid debugging of deserialization failures in tests
				try
				{
					// Use a repository-local path so test runners can find the dump reliably
					string repoRoot = "C:\\Users\\RMold\\OneDrive\\One Drive Documents\\SDC\\SDC Git Repo\\SDC.Schema";
					string dumpDir = System.IO.Path.Combine(repoRoot, "TestArtifacts");
					if (!System.IO.Directory.Exists(dumpDir)) System.IO.Directory.CreateDirectory(dumpDir);
					string dumpPath = System.IO.Path.Combine(dumpDir, "SdcSerializerJson_DeserializeError.json");
					string errPath = System.IO.Path.Combine(dumpDir, "SdcSerializerJson_DeserializeError.txt");
					System.IO.File.WriteAllText(dumpPath, input, System.Text.Encoding.UTF8);
					System.IO.File.WriteAllText(errPath, ex.ToString(), System.Text.Encoding.UTF8);
					throw new JsonSerializationException($"Deserialization failed. Input dumped to: {dumpPath}; exception written to: {errPath}", ex);
				}
				catch
				{
					throw;
				}
			}
		}
		#endregion

		// Contract resolver that deserializes by setting backing fields directly
		// This avoids invoking property setters (which perform validation and
		// tree-mutation logic) during deserialization. For generated xsd2code++ classes
		// the private backing fields use the convention: _{propertyName}
		class SdcNoSetterContractResolver : Newtonsoft.Json.Serialization.DefaultContractResolver
		{
			protected override Newtonsoft.Json.Serialization.JsonProperty CreateProperty(System.Reflection.MemberInfo member, Newtonsoft.Json.MemberSerialization memberSerialization)
			{
				var prop = base.CreateProperty(member, memberSerialization);
				// Only try to replace the value provider for properties that are writable
				if (prop.Writable)
				{
					var declaring = member.DeclaringType;
					if (declaring != null)
					{
						string name = member.Name; // property name as declared
						// candidates for backing field names
						string[] candidates = new[] { "_" + name, "_" + (char.ToLowerInvariant(name[0]) + name.Substring(1)) };
						System.Reflection.FieldInfo? field = null;
						foreach (var c in candidates)
						{
							field = declaring.GetField(c, System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
							if (field != null) break;
						}
						if (field != null)
						{
							prop.ValueProvider = new Newtonsoft.Json.Serialization.ReflectionValueProvider(field);
						}
					}
				}
				return prop;
			}
		}

		public static void SaveToFileJson<T>(string fileName, T obj)
		{
			System.IO.StreamWriter streamWriter = null;
			try
			{
				string xmlString = SerializeJson<T>(obj);
				System.IO.FileInfo xmlFile = new System.IO.FileInfo(fileName);
				streamWriter = xmlFile.CreateText();
				streamWriter.WriteLine(xmlString);
				streamWriter.Close();
			}
			finally
			{
				if ((streamWriter != null))
				{
					streamWriter.Dispose();
				}
			}
		}

		public static T LoadFromFileJson(string fileName)
		{
			System.IO.FileStream file = null;
			System.IO.StreamReader sr = null;
			try
			{
				file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
				sr = new System.IO.StreamReader(file);
				string xmlString = sr.ReadToEnd();
				sr.Close();
				file.Close();

				BaseType.ResetLastTopNode();
				T output = DeserializeJson<T>(xmlString);
				BaseType.ResetLastTopNode();
				return output;
			}
			finally
			{
				if ((file != null))
				{
					file.Dispose();
				}
				if ((sr != null))
				{
					sr.Dispose();
				}
			}
		}
	}

}
#pragma warning restore
