// ------------------------------------------------------------------------------
//  HAND-CORRECTED, FORMERLY AUTO-GENERATED FILE — DO NOT TREAT AS PRISTINE GENERATED CODE.
//
//  Origin: Generated by Xsd2Code++. Version 6.0.64.0. www.xsd2code.com
//  Original location: SDC.Schema/SDC.Schema/SDC Unmodified Classes/DataTypes_DEType.cs
//  Moved + corrected: 2026-06-23 (rlm / date-time validation work, GitHub issue #10).
//
//  WHY THIS FILE WAS MOVED OUT OF "SDC Unmodified Classes":
//  The generated DataTypes_DEType.Item polymorphic choice had two broken [XmlElement]
//  bindings that made three datatypes impossible to attach via the standard tree builder
//  (the by-CLR-type element-name resolver found 2 matches for gMonth_DEtype and 0 matches
//  for gYearMonth_DEtype / dayTimeDuration_DEtype). See the annotated edit site below.
//  Because it is now hand-maintained it MUST NOT live in the pristine "SDC Unmodified
//  Classes" folder, so it was relocated here via `git mv` (history preserved).
//
//  REGEN SURVIVAL (IMPORTANT — read before re-running xsd2code++):
//  A future xsd2code++ regeneration will emit a FRESH, UNCORRECTED DataTypes_DEType.cs
//  back into "SDC Unmodified Classes". Because both folders are compiled and this is a
//  `partial class` defining the `Item` property, that regenerated copy will collide with
//  this one (duplicate member) and FAIL THE BUILD — a deliberate, loud safety net.
//  After any regen you MUST: (1) delete the regenerated SDC Unmodified Classes copy, and
//  (2) re-apply the two corrections marked "ISSUE #10 HAND-CORRECTION" below to the new
//  output, then keep the corrected file here. See the README in this folder.
// ------------------------------------------------------------------------------
#pragma warning disable
namespace SDC.Schema
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Specialized;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Globalization;
using System.Xml;
using Newtonsoft.Json.Bson;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.IO;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

/// <summary>
/// Represents the SDC Response element, when serialized to XML.<br/>
/// Multiple kinds of SDC data type objects may attach to this object's Item property.<br/>
/// SDC datatypes for Data Entry (DE), based mostly on W3C specifications. Uses base _attributes and Extension capability to enhance the list of Data Types. Includes additonal metadata to specify data input restrictions for data entry forms, and to aid in validation of SDC form responses in SDC XML instance documents.
/// Must be one of the following:
/// --HTML (HTML_DEtype)
/// --XML (XML_DEtype)
/// --anyType (anyType_DEtype)
/// --anyURI (anyURI_DEtype)
/// --base64Binary (base64Binary_DEtype)
/// --boolean (boolean_DEtype)
/// --byte (byte_DEtype)
/// --date (date_DEtype)
/// --dateTime (dateTime_DEtype)
/// --dateTimeStamp (dateTimeStamp_DEtype)
/// --decimal (decimal_DEtype)
/// --double (double_DEtype)
/// --duration (duration_DEtype)
/// --dayTimeDuration (dayTimeDuration_DEtype)
/// --float (float_DEtype)
/// --gDay (gDay_DEtype)
/// --gMonth (gMonth_DEtype)
/// --gMonthDay (gMonthDay_DEtype)
/// --gYear (gYear_DEtype)
/// --gYearMonth (gYearMonth_DEtype)
/// --hexBinary (hexBinary_DEtype)
/// --int (int_DEtype)
/// --integer (integer_DEtype)
/// --long (long_DEtype)
/// --negativeInteger (negativeInteger_DEtype)
/// --nonNegativeInteger (nonNegativeInteger_DEtype)
/// --nonPositiveInteger (nonPositiveInteger_DEtype)
/// --positiveInteger (positiveInteger_DEtype)
/// --short (short_DEtype)
/// --string (string_DEtype)
/// --time (time_DEtype)
/// --unsignedByte (unsignedByte_DEtype)
/// --unsignedInt (unsignedInt_DEtype)
/// --unsignedLong (unsignedLong_DEtype)
/// --unsignedShort (unsignedShort_DEtype)
/// --yearMonthDuration (yearMonthDuration_DEtype)
/// </summary>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
[Serializable]
[DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="urn:ihe:qrph:sdc:2016")]
[JsonObject("DataTypes_DEType")]
public partial class DataTypes_DEType : ExtensionBaseType
{
    #region Private fields
    protected internal bool _shouldSerializeItemElementName;
    private BaseType _item;
    private ItemChoiceType2 _itemElementName;
    #endregion
    
    [XmlElement("HTML", typeof(HTML_DEtype), IsNullable=true, Order=0)]
    [XmlElement("XML", typeof(XML_DEtype), IsNullable=true, Order=0)]
    [XmlElement("anyType", typeof(anyType_DEtype), IsNullable=true, Order=0)]
    [XmlElement("anyURI", typeof(anyURI_DEtype), IsNullable=true, Order=0)]
    [XmlElement("base64Binary", typeof(base64Binary_DEtype), IsNullable=true, Order=0)]
    [XmlElement("boolean", typeof(boolean_DEtype), IsNullable=true, Order=0)]
    [XmlElement("byte", typeof(byte_DEtype), IsNullable=true, Order=0)]
    [XmlElement("date", typeof(date_DEtype), IsNullable=true, Order=0)]
    [XmlElement("dateTime", typeof(dateTime_DEtype), IsNullable=true, Order=0)] //Was dateTimeStamp_DEtype  RM 2023_02_21
	[XmlElement("dateTimeStamp", typeof(dateTimeStamp_DEtype), IsNullable=true, Order=0)]
    [XmlElement("decimal", typeof(decimal_DEtype), IsNullable=true, Order=0)]
    [XmlElement("double", typeof(double_DEtype), IsNullable=true, Order=0)]
    [XmlElement("duration", typeof(duration_DEtype), IsNullable=true, Order=0)]
    // ===== ISSUE #10 HAND-CORRECTION (2026-06-23) =====
    // ADDED: the generated choice had NO binding for the "dayTimeDuration" element at all
    // (only "duration" and "yearMonthDuration" existed), so a dayTimeDuration_DEtype node
    // could not be resolved to an element name and threw on attach. xs:dayTimeDuration is a
    // first-class restricted subtype of xs:duration and needs its own element binding.
    [XmlElement("dayTimeDuration", typeof(dayTimeDuration_DEtype), IsNullable=true, Order=0)]
    // ===== end ISSUE #10 HAND-CORRECTION =====
    [XmlElement("float", typeof(float_DEtype), IsNullable=true, Order=0)]
    [XmlElement("gDay", typeof(gDay_DEtype), IsNullable=true, Order=0)]
    [XmlElement("gMonth", typeof(gMonth_DEtype), IsNullable=true, Order=0)]
    [XmlElement("gMonthDay", typeof(gMonthDay_DEtype), IsNullable=true, Order=0)]
    [XmlElement("gYear", typeof(gYear_DEtype), IsNullable=true, Order=0)]
    // ===== ISSUE #10 HAND-CORRECTION (2026-06-23) =====
    // WAS: [XmlElement("gYearMonth", typeof(gMonth_DEtype), ...)]  <-- WRONG CLR type.
    // The "gYearMonth" element was bound to gMonth_DEtype (the SAME type as the "gMonth"
    // element above), so (a) gMonth_DEtype matched two elements -> "could not determine a
    // unique XmlElementAttribute Type match", and (b) gYearMonth_DEtype matched zero
    // elements -> "a property with a unique type match could not be found". Corrected to the
    // proper gYearMonth_DEtype below. Suspected cause: an earlier .NET/xsd2code++ generation
    // could not distinguish these structurally-similar CLR types and collapsed both elements
    // onto gMonth_DEtype.
    [XmlElement("gYearMonth", typeof(gYearMonth_DEtype), IsNullable=true, Order=0)]
    // ===== end ISSUE #10 HAND-CORRECTION =====
    [XmlElement("hexBinary", typeof(hexBinary_DEtype), IsNullable=true, Order=0)]
    [XmlElement("int", typeof(int_DEtype), IsNullable=true, Order=0)]
    [XmlElement("integer", typeof(integer_DEtype), IsNullable=true, Order=0)]
    [XmlElement("long", typeof(long_DEtype), IsNullable=true, Order=0)]
    [XmlElement("negativeInteger", typeof(negativeInteger_DEtype), IsNullable=true, Order=0)]
    [XmlElement("nonNegativeInteger", typeof(nonNegativeInteger_DEtype), IsNullable=true, Order=0)]
    [XmlElement("nonPositiveInteger", typeof(nonPositiveInteger_DEtype), IsNullable=true, Order=0)]
    [XmlElement("positiveInteger", typeof(positiveInteger_DEtype), IsNullable=true, Order=0)]
    [XmlElement("short", typeof(short_DEtype), IsNullable=true, Order=0)]
    [XmlElement("string", typeof(string_DEtype), IsNullable=true, Order=0)]
    [XmlElement("time", typeof(time_DEtype), IsNullable=true, Order=0)]
    [XmlElement("unsignedByte", typeof(unsignedByte_DEtype), IsNullable=true, Order=0)]
    [XmlElement("unsignedInt", typeof(unsignedInt_DEtype), IsNullable=true, Order=0)]
    [XmlElement("unsignedLong", typeof(unsignedLong_DEtype), IsNullable=true, Order=0)]
    [XmlElement("unsignedShort", typeof(unsignedShort_DEtype), IsNullable=true, Order=0)]
    [XmlElement("yearMonthDuration", typeof(yearMonthDuration_DEtype), IsNullable=true, Order=0)]
    [XmlChoiceIdentifierAttribute("ItemElementName")]
    public virtual BaseType Item
    {
        get
        {
            return _item;
        }
        set
        {
            if ((_item == value))
            {
                return;
            }
            if (((_item == null) 
                        || (_item.Equals(value) != true)))
            {
                _item = value;
                OnPropertyChanged("Item", value);
            }
        }
    }
    
    [XmlElement(Order=1)]
    [XmlIgnore]
    public virtual ItemChoiceType2 ItemElementName
    {
        get
        {
            return _itemElementName;
        }
        set
        {
            if ((_itemElementName.Equals(value) != true))
            {
                _itemElementName = value;
                OnPropertyChanged("ItemElementName", value);
            }
            _shouldSerializeItemElementName = true;
        }
    }
    
    /// <summary>
    /// Test whether ItemElementName should be serialized
    /// </summary>
    public virtual bool ShouldSerializeItemElementName()
    {
        if (_shouldSerializeItemElementName)
        {
            return true;
        }
        return (_itemElementName != default(ItemChoiceType2));
    }
    
    /// <summary>
    /// Test whether Item should be serialized
    /// </summary>
    public virtual bool ShouldSerializeItem()
    {
        return (_item != null);
    }
}
}
#pragma warning restore
